# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build website 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm ci
      working-directory: ./.website
    - run: npm run build:gh-pages
      working-directory: ./.website
    - run: rm -r server 3rdpartylicenses.txt prerendered-routes.json
      working-directory: ./docs
    - run: mv browser/* ./
      working-directory: ./docs
    - run: cp index.html 404.html
      working-directory: ./docs
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "docs/"
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write  
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # to verify the deployment originates from an appropriate source
    steps:
    - name: Deploy artifact on Github Pages
      id: deployment
      uses: actions/deploy-pages@v4
